### ISSUE TITLE
Unable to install logstash-output-amazon-es plugin in Windows

### ISSUE THREAD

**Issue by shashankshekhar92** [awslabs/logstash-output-amazon_es#136]
I am trying to install logstash-output-amazon-es plugin in Windows using power shell and I am getting the following error

PS C:\logstash-7.4.2> bin/logstash-plugin install logstash-output-amazon_es -v 6.4.0
Validating logstash-output-amazon_es
Found logstash-output-amazon_es (6.4.1), but was for platform x86_64-linux
Validating -v
Plugin -v does not exist
ERROR: Installation aborted, verification failed for -v

**Comment by treddeni-amazon** [comment]
You need to put the options before the plugin name in the command and the option is `--version`

This should work for you: 
`bin/logstash-plugin install --version 6.4.0 logstash-output-amazon_es`

> Usage:
    bin/logstash-plugin install [OPTIONS] [PLUGIN] ...

> Parameters:
    [PLUGIN] ...                  plugin name(s) or file

> Options:
    --version VERSION             version of the plugin to install
    --[no-]verify                 verify plugin validity before installation (default: true)
    --preserve                    preserve current gem options (default: false)
    --development                 install all development dependencies of currently installed plugins (default: false)
    --local                       force local-only plugin installation. see bin/logstash-plugin package|unpack (default: false)
    -h, --help                    print help

**Comment by marabesi** [comment]
Worked perfectly with @treddeni-amazon comment (I am using docker), in my case I had to:

```
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    env_file:
      - .env
    command: bash -c "logstash-plugin install --version 6.4.0 logstash-output-amazon_es && logstash -f /usr/share/logstash/pipeline/logstash.conf"
```
